name = input("what is your name: ")
age = int(input("how old are you: "))
year = str((2014 - age)+100)
thisyear = int(input("what year is it: "))
print(name + " will be 100 years old in the year " + year)